jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: docker build -f script/Dockerfile.bionic -t cpp_concurrency .
    displayName: run docker-bionic
