jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: git submodule update --init
    displayName: initialize submodule

  - task: CMake@1
    inputs:
      workingDirectory: build
      cmakeArgs: ..\test
    displayName: CMake catch_test

  - task: MSBuild@1
    inputs: 
      solution: .\build\catch_test.sln
    displayName: MSBuild catch_test

  - script: .\build\Debug\catch_test.exe
    displayName: Start catch_test

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: 'x64'
  
  - script: python -m script.merge
    displayName: Remerge concurrency.hpp

  - task: CMake@1
    inputs:
      workingDirectory: build
      cmakeArgs: ..\sample
    displayName: CMake sample

  - task: MSBuild@1
    inputs:
      solution: .\build\sample.sln
    displayName: MSBuild sample
  
  - script: .\build\Debug\dir_size.exe .
    displayName: Start dir_size
  
  - script: .\build\Debug\tick.exe
    displayName: start tick
