jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: git submodule update --init
    displayName: Initialize submodule

  - task: CMake@1
    inputs:
      workingDirectory: .\test\build
      cmakeArgs: ..\
    displayName: CMake catch_test

  - task: MSBuild@1
    inputs: 
      solution: .\test\build\catch_test.sln
    displayName: MSBuild catch_test

  - script: .\test\build\Debug\catch_test.exe
    displayName: Start catch_test

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: 'x64'
  
  - script: python -m script.merge
    displayName: Remerge concurrency.hpp

  - task: CMake@1
    inputs:
      workingDirectory: .\sample\build
      cmakeArgs: ..\
    displayName: CMake sample

  - task: MSBuild@1
    inputs:
      solution: .\sample\build\sample.sln
    displayName: MSBuild sample
  
  - script: .\sample\build\Debug\dir_size.exe ..
    displayName: Start dir_size
  
  - script: .\sample\build\Debug\tick.exe
    displayName: Start tick
