jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: git submodule update --init
    displayName: initialize submodule

  - task: CMake@1
    inputs:
      workingDirectory: build
      cmakeArgs: .\test
    displayName: CMake catch_test

  - task: MSBuild@1
    inputs: 
      solution: .\build\catch_test.sln
    displayName: MSBuild catch_test

  - script: .\build\Debug\catch_test.exe
    displayName: Start catch_test
